name: "Ephemeral GCE GitHub self-hosted runner"
description: >-
  Creates ephemeral GCE based GitHub Action self-hosted runner.
  It uses startup script to bootstrap the VM.
author: Rafal Wojdyla
branding:
  icon: triangle
  color: purple
inputs:
  arm:
    description: "Whether the GitHub actions should use arm64 binaries."
    default: false
    required: false
  mig:
    description: "Managed instance group name to create the machine in."
    required: true
  region:
    description: "The region where to create the VM in."
    required: true

outputs:
  label:
    description: >-
      Unique runner label. This label can be used to request a specific
      runner for the workflow job.
    value: ${{ steps.gce-github-runner-script.outputs.label }}
runs:
  using: "composite"
  steps:
    - id: gce-github-runner-script
      run: >
        ${{ github.action_path }}/action.sh
        --arm=${{ inputs.arm }}
        --mig=${{ inputs.mig }}
        --region=${{ inputs.region }}
      shell: bash
